Added the pin driver and certain needed head file
picasso250/spring12 pull request #6
Opened 2019-02-15 13:26 UTC by BobGuo0714

已经添加撞针驱动程序和必要的头文件，请合并到主干，让奋斗了36小时的救援队能好好回去陪陪家人，让CN171-11小队跑到地下城避难

2019-02-15 13:29 UTC, BobGuo0714 commented
联合政府技术委员会提醒您：  
代码千万条  
除虫第一条  
代码不清洁  
乙方两行泪

2019-02-20 02:52 UTC, panda361 requested changes
You're missing a semicolon(23333

2019-02-20 02:52 UTC, panda361 commented on twelve_biubiu.c
> +    engine_ensure_shutdown()
There's a missing semicolon ;)
```suggestion
    engine_ensure_shutdown();
```

2019-02-21 14:43 UTC, lhy0403 commented
[merged in @lhy0403 's repo]

2019-06-27 13:09 UTC, picasso250 commented on twelve_biubiu.c
> +    engine_ensure_shutdown()
此处确实少了一个分号

2020-01-12 04:50 UTC, closed without merging